<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Modelado | MEMORIA.knit</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Modelado | MEMORIA.knit" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Modelado | MEMORIA.knit" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="preprocesado-de-datos..html"/>
<link rel="next" href="evaluación.html"/>
<script src="libs/header-attrs-2.11.3/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="memoria.html"><a href="memoria.html"><i class="fa fa-check"></i><b>1</b> MEMORIA</a></li>
<li class="chapter" data-level="2" data-path="introducción.html"><a href="introducción.html"><i class="fa fa-check"></i><b>2</b> Introducción</a></li>
<li class="chapter" data-level="3" data-path="objetivos.html"><a href="objetivos.html"><i class="fa fa-check"></i><b>3</b> Objetivos</a></li>
<li class="chapter" data-level="4" data-path="datos.html"><a href="datos.html"><i class="fa fa-check"></i><b>4</b> Datos</a></li>
<li class="chapter" data-level="5" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html"><i class="fa fa-check"></i><b>5</b> Preprocesado de datos.</a>
<ul>
<li class="chapter" data-level="5.1" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#particiones."><i class="fa fa-check"></i><b>5.1</b> Particiones.</a></li>
<li class="chapter" data-level="5.2" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#eda.-exploratory-data-analysis."><i class="fa fa-check"></i><b>5.2</b> EDA. Exploratory Data Analysis.</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#letalidad"><i class="fa fa-check"></i><b>5.2.1</b> Letalidad:</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#correlación-entre-las-variables."><i class="fa fa-check"></i><b>5.3</b> Correlación entre las variables.</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#forma-del-sombrero-forma_s"><i class="fa fa-check"></i><b>5.3.1</b> Forma del sombrero (Forma_S)</a></li>
<li class="chapter" data-level="5.3.2" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#cutícula"><i class="fa fa-check"></i><b>5.3.2</b> Cutícula</a></li>
<li class="chapter" data-level="5.3.3" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#color-del-sombrero-color_s"><i class="fa fa-check"></i><b>5.3.3</b> Color del sombrero (Color_S)</a></li>
<li class="chapter" data-level="5.3.4" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#escamas"><i class="fa fa-check"></i><b>5.3.4</b> Escamas</a></li>
<li class="chapter" data-level="5.3.5" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#olor"><i class="fa fa-check"></i><b>5.3.5</b> Olor</a></li>
<li class="chapter" data-level="5.3.6" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#fijación-de-las-láminas-fijacion_l"><i class="fa fa-check"></i><b>5.3.6</b> Fijación de las láminas (Fijacion_L)</a></li>
<li class="chapter" data-level="5.3.7" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#espacio-entre-láminas-espacio_l"><i class="fa fa-check"></i><b>5.3.7</b> Espacio entre láminas (Espacio_L)</a></li>
<li class="chapter" data-level="5.3.8" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#tamaño-de-las-láminas-tamaño_l"><i class="fa fa-check"></i><b>5.3.8</b> Tamaño de las láminas (Tamaño_L)</a></li>
<li class="chapter" data-level="5.3.9" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#color-de-las-láminas-color_l"><i class="fa fa-check"></i><b>5.3.9</b> Color de las láminas (Color_L)</a></li>
<li class="chapter" data-level="5.3.10" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#forma-del-tallo-forma_t"><i class="fa fa-check"></i><b>5.3.10</b> Forma del tallo (Forma_T)</a></li>
<li class="chapter" data-level="5.3.11" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#tallo-raíz-tallo_raiz"><i class="fa fa-check"></i><b>5.3.11</b> Tallo-Raíz (Tallo_raiz)</a></li>
<li class="chapter" data-level="5.3.12" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#superficie-del-tallo-por-encima-del-anillo-superficie_t1"><i class="fa fa-check"></i><b>5.3.12</b> Superficie del tallo por encima del anillo (Superficie_T1)</a></li>
<li class="chapter" data-level="5.3.13" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#superficie-del-tallo-por-debajo-del-anillo-superficie_t2"><i class="fa fa-check"></i><b>5.3.13</b> Superficie del tallo por debajo del anillo (Superficie_T2)</a></li>
<li class="chapter" data-level="5.3.14" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#color-del-tallo-por-encima-del-anillo-color_t1"><i class="fa fa-check"></i><b>5.3.14</b> Color del tallo por encima del anillo (Color_T1)</a></li>
<li class="chapter" data-level="5.3.15" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#color-del-tallo-por-debajo-del-anillo-color_t2"><i class="fa fa-check"></i><b>5.3.15</b> Color del tallo por debajo del anillo (Color_T2)</a></li>
<li class="chapter" data-level="5.3.16" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#color-del-volva-color_v"><i class="fa fa-check"></i><b>5.3.16</b> Color del volva (Color_V)</a></li>
<li class="chapter" data-level="5.3.17" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#número-de-anillos-n_anillos"><i class="fa fa-check"></i><b>5.3.17</b> Número de anillos (N_anillos)</a></li>
<li class="chapter" data-level="5.3.18" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#tipo-de-anillo-tipo_anillo"><i class="fa fa-check"></i><b>5.3.18</b> Tipo de anillo (Tipo_anillo)</a></li>
<li class="chapter" data-level="5.3.19" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#color-de-las-esporas"><i class="fa fa-check"></i><b>5.3.19</b> Color de las esporas</a></li>
<li class="chapter" data-level="5.3.20" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#población"><i class="fa fa-check"></i><b>5.3.20</b> Población</a></li>
<li class="chapter" data-level="5.3.21" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#habitat"><i class="fa fa-check"></i><b>5.3.21</b> Habitat</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#componentes-principales"><i class="fa fa-check"></i><b>5.4</b> Componentes principales</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#proceso-previo"><i class="fa fa-check"></i><b>5.4.1</b> Proceso previo</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#transformación-de-variables"><i class="fa fa-check"></i><b>5.5</b> Transformación de variables</a></li>
<li class="chapter" data-level="5.6" data-path="preprocesado-de-datos..html"><a href="preprocesado-de-datos..html#imputación-de-datos-datos-faltantes"><i class="fa fa-check"></i><b>5.6</b> Imputación de datos (datos faltantes)</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modelado.html"><a href="modelado.html"><i class="fa fa-check"></i><b>6</b> Modelado</a>
<ul>
<li class="chapter" data-level="6.1" data-path="modelado.html"><a href="modelado.html#análisis-clúster"><i class="fa fa-check"></i><b>6.1</b> Análisis Clúster</a></li>
<li class="chapter" data-level="6.2" data-path="modelado.html"><a href="modelado.html#k-nn"><i class="fa fa-check"></i><b>6.2</b> k-NN</a></li>
<li class="chapter" data-level="6.3" data-path="modelado.html"><a href="modelado.html#arboles-de-decisión"><i class="fa fa-check"></i><b>6.3</b> Arboles de Decisión</a></li>
<li class="chapter" data-level="6.4" data-path="modelado.html"><a href="modelado.html#bosques-aleatorios"><i class="fa fa-check"></i><b>6.4</b> Bosques Aleatorios</a></li>
<li class="chapter" data-level="6.5" data-path="modelado.html"><a href="modelado.html#support-vector-machines"><i class="fa fa-check"></i><b>6.5</b> Support Vector Machines</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="evaluación.html"><a href="evaluación.html"><i class="fa fa-check"></i><b>7</b> Evaluación</a></li>
<li class="chapter" data-level="8" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html"><i class="fa fa-check"></i><b>8</b> Actualización del modelo…</a>
<ul>
<li class="chapter" data-level="8.1" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html#datos-sin-variable-olor"><i class="fa fa-check"></i><b>8.1</b> Datos sin variable <strong>Olor</strong></a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html#análisis-cluster"><i class="fa fa-check"></i><b>8.1.1</b> Análisis Cluster</a></li>
<li class="chapter" data-level="8.1.2" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html#k-nn-1"><i class="fa fa-check"></i><b>8.1.2</b> k-NN</a></li>
<li class="chapter" data-level="8.1.3" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html#arboles-de-decisión-1"><i class="fa fa-check"></i><b>8.1.3</b> Arboles de Decisión</a></li>
<li class="chapter" data-level="8.1.4" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html#bosques-aleatorios-1"><i class="fa fa-check"></i><b>8.1.4</b> Bosques Aleatorios</a></li>
<li class="chapter" data-level="8.1.5" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html#support-vector-machines-1"><i class="fa fa-check"></i><b>8.1.5</b> Support Vector Machines</a></li>
<li class="chapter" data-level="8.1.6" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html#evaluación-1"><i class="fa fa-check"></i><b>8.1.6</b> Evaluación</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html#datos-con-variable-olorn"><i class="fa fa-check"></i><b>8.2</b> Datos con variable <strong>Olor=n</strong></a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html#análisis-cluster-1"><i class="fa fa-check"></i><b>8.2.1</b> Análisis Cluster</a></li>
<li class="chapter" data-level="8.2.2" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html#k-nn-2"><i class="fa fa-check"></i><b>8.2.2</b> k-NN</a></li>
<li class="chapter" data-level="8.2.3" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html#arboles-de-decisión-2"><i class="fa fa-check"></i><b>8.2.3</b> Arboles de Decisión</a></li>
<li class="chapter" data-level="8.2.4" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html#bosques-aleatorios-2"><i class="fa fa-check"></i><b>8.2.4</b> Bosques Aleatorios</a></li>
<li class="chapter" data-level="8.2.5" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html#support-vector-machines-2"><i class="fa fa-check"></i><b>8.2.5</b> Support Vector Machines</a></li>
<li class="chapter" data-level="8.2.6" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html#evaluación-2"><i class="fa fa-check"></i><b>8.2.6</b> Evaluación</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="actualización-del-modelo.html"><a href="actualización-del-modelo.html#evaluación-de-los-tres-análisis"><i class="fa fa-check"></i><b>8.3</b> Evaluación de los tres análisis</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelado" class="section level1" number="6">
<h1><span class="header-section-number">6</span> Modelado</h1>
<div id="análisis-clúster" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> Análisis Clúster</h2>
<p>El análisis clúster es un conjunto de técnicas multivariantes utilizadas para clasificar a un conjunto de individuos en grupos homogéneos. Para determinar el número de grupos, realizamos cross-validation con nuestros datos de validación.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="modelado.html#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Números de clusters</span></span>
<span id="cb126-2"><a href="modelado.html#cb126-2" aria-hidden="true" tabindex="-1"></a>SSW <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">mode =</span> <span class="st">&quot;numeric&quot;</span>, <span class="at">length =</span> <span class="dv">15</span>)</span>
<span id="cb126-3"><a href="modelado.html#cb126-3" aria-hidden="true" tabindex="-1"></a>n<span class="ot">=</span><span class="fu">dim</span>(<span class="fu">prcomp</span>(setas60_validacion)<span class="sc">$</span>x)[<span class="dv">1</span>]</span>
<span id="cb126-4"><a href="modelado.html#cb126-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Variabilidad de todos los datos, es decir, todos los datos como un único cluster</span></span>
<span id="cb126-5"><a href="modelado.html#cb126-5" aria-hidden="true" tabindex="-1"></a>SSW[<span class="dv">1</span>] <span class="ot">&lt;-</span> (n <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">apply</span>(<span class="fu">prcomp</span>(setas60_validacion)<span class="sc">$</span>x,<span class="dv">2</span>,var)) </span>
<span id="cb126-6"><a href="modelado.html#cb126-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-7"><a href="modelado.html#cb126-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Variabilidad de cada modelo, desde 2 clusters hasta 15 clusters</span></span>
<span id="cb126-8"><a href="modelado.html#cb126-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">15</span>) SSW[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">kmeans</span>(<span class="fu">prcomp</span>(setas60_validacion)<span class="sc">$</span>x,<span class="at">centers=</span>i,<span class="at">nstart=</span><span class="dv">25</span>)<span class="sc">$</span>withinss)</span>
<span id="cb126-9"><a href="modelado.html#cb126-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-10"><a href="modelado.html#cb126-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Dibujamos un gráfico con el resultado</span></span>
<span id="cb126-11"><a href="modelado.html#cb126-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>, SSW, <span class="at">type=</span><span class="st">&quot;b&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Número de clusters&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Suma de cuadrados de los grupos&quot;</span>,<span class="at">pch=</span><span class="dv">19</span>, <span class="at">col=</span><span class="st">&quot;steelblue4&quot;</span>)</span></code></pre></div>
<p><img src="MEMORIA_files/figure-html/crossvalidation%20cluster-1.png" width="672" /></p>
<p>En el gráfico podemos observar que a partir de aplicar 5 clusters a nuestros datos la suma de los cuadrados se reduce en menor medida, por ello realizamos el análisis con ese número de clusters.</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="modelado.html#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Análisis cluster</span></span>
<span id="cb127-2"><a href="modelado.html#cb127-2" aria-hidden="true" tabindex="-1"></a>clusters.datos<span class="ot">=</span><span class="fu">kmeans</span>(<span class="fu">prcomp</span>(setas60_train)<span class="sc">$</span>x,<span class="at">centers=</span><span class="dv">5</span>,<span class="at">nstart=</span><span class="dv">25</span>)</span>
<span id="cb127-3"><a href="modelado.html#cb127-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(clusters.datos<span class="sc">$</span>cluster,setas_train<span class="sc">$</span>Letalidad)</span></code></pre></div>
<pre><code>##    
##        0    1
##   1  624  486
##   2  835    4
##   3 1059    5
##   4    4 1089
##   5    0  768</code></pre>
<p>Podemos ver que un clúster identificar correctamente a las setas venenosas mientras que el resto de clusters, las setas están un poco más repartidas, por ejemplo el clúster que reparte las setas de la forma 624-486 es menos específico que los clusters que reparten 835-4, 1059-5 y 4-1089.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="modelado.html#cb129-1" aria-hidden="true" tabindex="-1"></a>pca<span class="ot">=</span><span class="fu">prcomp</span>(setas60_train)<span class="sc">$</span>x</span>
<span id="cb129-2"><a href="modelado.html#cb129-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-3"><a href="modelado.html#cb129-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Gráfico de los cluster</span></span>
<span id="cb129-4"><a href="modelado.html#cb129-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">prcomp</span>(setas60_train)<span class="sc">$</span>x,<span class="at">main=</span><span class="st">&quot;Clusters&quot;</span>,<span class="at">type=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb129-5"><a href="modelado.html#cb129-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">dim</span>(setas60_train)[<span class="dv">1</span>]){</span>
<span id="cb129-6"><a href="modelado.html#cb129-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">points</span>(pca[i,<span class="dv">1</span>],pca[i,<span class="dv">2</span>],<span class="at">pch=</span><span class="dv">19</span>,<span class="at">col=</span>clusters.datos<span class="sc">$</span>cluster[i]<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb129-7"><a href="modelado.html#cb129-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb129-8"><a href="modelado.html#cb129-8" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>,   </span>
<span id="cb129-9"><a href="modelado.html#cb129-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">inset =</span> <span class="fl">0.01</span>, </span>
<span id="cb129-10"><a href="modelado.html#cb129-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>),</span>
<span id="cb129-11"><a href="modelado.html#cb129-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">fil =</span> <span class="fu">seq</span>(<span class="dv">2</span>,<span class="dv">6</span>))</span></code></pre></div>
<p><img src="MEMORIA_files/figure-html/grafico%20cluster%205-1.png" width="672" /></p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="modelado.html#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Gráfico por tipo de setas:</span></span>
<span id="cb130-2"><a href="modelado.html#cb130-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb130-3"><a href="modelado.html#cb130-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">prcomp</span>(setas60_train)<span class="sc">$</span>x,<span class="at">main=</span><span class="st">&quot;Clusters: setas comestibles&quot;</span>,<span class="at">type=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb130-4"><a href="modelado.html#cb130-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">dim</span>(setas60_train)[<span class="dv">1</span>]){</span>
<span id="cb130-5"><a href="modelado.html#cb130-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(setas_train[i,<span class="dv">1</span>]<span class="sc">==</span><span class="dv">0</span>){</span>
<span id="cb130-6"><a href="modelado.html#cb130-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">points</span>(pca[i,<span class="dv">1</span>],pca[i,<span class="dv">2</span>],<span class="at">pch=</span><span class="dv">19</span>,<span class="at">col=</span>clusters.datos<span class="sc">$</span>cluster[i]<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb130-7"><a href="modelado.html#cb130-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb130-8"><a href="modelado.html#cb130-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb130-9"><a href="modelado.html#cb130-9" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>,   </span>
<span id="cb130-10"><a href="modelado.html#cb130-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">inset =</span> <span class="fl">0.01</span>, </span>
<span id="cb130-11"><a href="modelado.html#cb130-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>),</span>
<span id="cb130-12"><a href="modelado.html#cb130-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">fil =</span> <span class="fu">seq</span>(<span class="dv">2</span>,<span class="dv">6</span>))</span>
<span id="cb130-13"><a href="modelado.html#cb130-13" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">prcomp</span>(setas60_train)<span class="sc">$</span>x,<span class="at">main=</span><span class="st">&quot;Clusters: setas venenosas&quot;</span>,<span class="at">type=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb130-14"><a href="modelado.html#cb130-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">dim</span>(setas60_train)[<span class="dv">1</span>]){</span>
<span id="cb130-15"><a href="modelado.html#cb130-15" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(setas_train[i,<span class="dv">1</span>]<span class="sc">==</span><span class="dv">1</span>){</span>
<span id="cb130-16"><a href="modelado.html#cb130-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">points</span>(pca[i,<span class="dv">1</span>],pca[i,<span class="dv">2</span>],<span class="at">pch=</span><span class="dv">19</span>,<span class="at">col=</span>clusters.datos<span class="sc">$</span>cluster[i]<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb130-17"><a href="modelado.html#cb130-17" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb130-18"><a href="modelado.html#cb130-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb130-19"><a href="modelado.html#cb130-19" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>,   </span>
<span id="cb130-20"><a href="modelado.html#cb130-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">inset =</span> <span class="fl">0.01</span>, </span>
<span id="cb130-21"><a href="modelado.html#cb130-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>),</span>
<span id="cb130-22"><a href="modelado.html#cb130-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">fil =</span> <span class="fu">seq</span>(<span class="dv">2</span>,<span class="dv">6</span>))</span></code></pre></div>
<p><img src="MEMORIA_files/figure-html/grafico%20cluster%205-2.png" width="672" /></p>
<p>El objetivo de los gráficos que están a par es ver que debería estar cada color solo en uno de ellos pero podemos ver lo que hemos comentado antes, tenemos bastante bien clasificados las setas venenosas en un cluster pero uno de los clusters con setas mezcladas no clasifica tan bien como los otros, luego habría que estudiar ese para ver como diferenciar las venenosas de las comestibles.</p>
<p>Vamos a realizar otro análisis clúster pero aumentando el número de clusters con la intención de con un número mayor de clusters se clasifiquen mejor las setas.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="modelado.html#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Análisis cluster</span></span>
<span id="cb131-2"><a href="modelado.html#cb131-2" aria-hidden="true" tabindex="-1"></a>clusters.datos.train<span class="ot">=</span><span class="fu">kmeans</span>(<span class="fu">prcomp</span>(setas60_train)<span class="sc">$</span>x,<span class="at">centers=</span><span class="dv">8</span>,<span class="at">nstart=</span><span class="dv">25</span>)</span>
<span id="cb131-3"><a href="modelado.html#cb131-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(clusters.datos.train<span class="sc">$</span>cluster,setas_train<span class="sc">$</span>Letalidad)</span></code></pre></div>
<pre><code>##    
##        0    1
##   1  124  270
##   2    4  569
##   3  452    3
##   4  435  203
##   5  463    7
##   6    0  768
##   7 1044    0
##   8    0  532</code></pre>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="modelado.html#cb133-1" aria-hidden="true" tabindex="-1"></a>pca<span class="ot">=</span><span class="fu">prcomp</span>(setas60_train)<span class="sc">$</span>x</span>
<span id="cb133-2"><a href="modelado.html#cb133-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-3"><a href="modelado.html#cb133-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Gráfico de los cluster</span></span>
<span id="cb133-4"><a href="modelado.html#cb133-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">prcomp</span>(setas60_train)<span class="sc">$</span>x,<span class="at">main=</span><span class="st">&quot;Clusters&quot;</span>,<span class="at">type=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb133-5"><a href="modelado.html#cb133-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">dim</span>(setas60_train)[<span class="dv">1</span>]){</span>
<span id="cb133-6"><a href="modelado.html#cb133-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">points</span>(pca[i,<span class="dv">1</span>],pca[i,<span class="dv">2</span>],<span class="at">pch=</span><span class="dv">19</span>,<span class="at">col=</span>clusters.datos.train<span class="sc">$</span>cluster[i]<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb133-7"><a href="modelado.html#cb133-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb133-8"><a href="modelado.html#cb133-8" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>,   </span>
<span id="cb133-9"><a href="modelado.html#cb133-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">inset =</span> <span class="fl">0.01</span>, </span>
<span id="cb133-10"><a href="modelado.html#cb133-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>),</span>
<span id="cb133-11"><a href="modelado.html#cb133-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">fil =</span> <span class="fu">seq</span>(<span class="dv">2</span>,<span class="dv">9</span>))</span></code></pre></div>
<p><img src="MEMORIA_files/figure-html/grafico%20cluster%208-1.png" width="672" /></p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="modelado.html#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Gráfico por tipo de setas:</span></span>
<span id="cb134-2"><a href="modelado.html#cb134-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb134-3"><a href="modelado.html#cb134-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">prcomp</span>(setas60_train)<span class="sc">$</span>x,<span class="at">main=</span><span class="st">&quot;Clusters: setas comestibles&quot;</span>,<span class="at">type=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb134-4"><a href="modelado.html#cb134-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">dim</span>(setas60_train)[<span class="dv">1</span>]){</span>
<span id="cb134-5"><a href="modelado.html#cb134-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(setas_train[i,<span class="dv">1</span>]<span class="sc">==</span><span class="dv">0</span>){</span>
<span id="cb134-6"><a href="modelado.html#cb134-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">points</span>(pca[i,<span class="dv">1</span>],pca[i,<span class="dv">2</span>],<span class="at">pch=</span><span class="dv">19</span>,<span class="at">col=</span>clusters.datos.train<span class="sc">$</span>cluster[i]<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb134-7"><a href="modelado.html#cb134-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb134-8"><a href="modelado.html#cb134-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb134-9"><a href="modelado.html#cb134-9" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>,   </span>
<span id="cb134-10"><a href="modelado.html#cb134-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">inset =</span> <span class="fl">0.01</span>, </span>
<span id="cb134-11"><a href="modelado.html#cb134-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>),</span>
<span id="cb134-12"><a href="modelado.html#cb134-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">fil =</span> <span class="fu">seq</span>(<span class="dv">2</span>,<span class="dv">9</span>))</span>
<span id="cb134-13"><a href="modelado.html#cb134-13" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">prcomp</span>(setas60_train)<span class="sc">$</span>x,<span class="at">main=</span><span class="st">&quot;Clusters: setas venenosas&quot;</span>,<span class="at">type=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb134-14"><a href="modelado.html#cb134-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">dim</span>(setas60_train)[<span class="dv">1</span>]){</span>
<span id="cb134-15"><a href="modelado.html#cb134-15" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(setas_train[i,<span class="dv">1</span>]<span class="sc">==</span><span class="dv">1</span>){</span>
<span id="cb134-16"><a href="modelado.html#cb134-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">points</span>(pca[i,<span class="dv">1</span>],pca[i,<span class="dv">2</span>],<span class="at">pch=</span><span class="dv">19</span>,<span class="at">col=</span>clusters.datos.train<span class="sc">$</span>cluster[i]<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb134-17"><a href="modelado.html#cb134-17" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb134-18"><a href="modelado.html#cb134-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb134-19"><a href="modelado.html#cb134-19" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>,   </span>
<span id="cb134-20"><a href="modelado.html#cb134-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">inset =</span> <span class="fl">0.01</span>, </span>
<span id="cb134-21"><a href="modelado.html#cb134-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>),</span>
<span id="cb134-22"><a href="modelado.html#cb134-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">fil =</span> <span class="fu">seq</span>(<span class="dv">2</span>,<span class="dv">9</span>))</span></code></pre></div>
<p><img src="MEMORIA_files/figure-html/grafico%20cluster%208-2.png" width="672" /></p>
<p>Vemos que tras realizar el análisis clúster con 8 grupos, no obtenemos tan claramente la clasificación de setas que buscamos pero ahora tenemos dos grupos bien diferenciados, que son los que vemos en el gráfico del análisis de componentes principales, y aparece un tercer clúster que clasifica correctamente la toxicidad de la setas dentro de la maraña de datos pero el resto están mezclados entre los clusters y habría que analizar cada uno de ellos para poder obtener alguna información más.</p>
<p>Con este análisis también vemos que a pesar de haber aumentado el número de clusters, no conseguimos una clasificación perfecta, por ello sacamos la conclusión que no vamos a clasificar todas las setas correctamente y cometeremos un cierto error mediante este modelo.</p>
</div>
<div id="k-nn" class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> k-NN</h2>
<p>El algoritmo k-NN clasifica cada dato nuevo en el grupo que corresponda, según los k vecinos más cercanos que tenga de un grupo o de otro. Es decir, calcula la distancia del elemento nuevo a cada uno de los existentes, y ordena dichas distancias de menor a mayor para ir seleccionando el grupo al que pertenecer. Este grupo será, por tanto, el de mayor frecuencia con menores distancias.</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="modelado.html#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Buscamos los vecinos más cercanos</span></span>
<span id="cb135-2"><a href="modelado.html#cb135-2" aria-hidden="true" tabindex="-1"></a>prediccion_knn<span class="ot">=</span><span class="fu">knn</span>(setas60_train,setas60_test,<span class="at">cl=</span>setas_train<span class="sc">$</span>Letalidad,<span class="at">k=</span><span class="dv">1</span>)</span>
<span id="cb135-3"><a href="modelado.html#cb135-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(prediccion_knn,setas_test<span class="sc">$</span>Letalidad)</span></code></pre></div>
<pre><code>##               
## prediccion_knn   0   1
##              0 836   1
##              1   2 785</code></pre>
<p>La predicción con el 1-vecino más próximo, es bastante buena, lo podemos ver a simple vista en la tabla. Pero vamos a realizar un análisis con distintas medidas de precisión.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="modelado.html#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exactitud/Error</span></span>
<span id="cb137-2"><a href="modelado.html#cb137-2" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">=</span> <span class="fu">sum</span>(prediccion_knn <span class="sc">==</span> setas_test<span class="sc">$</span>Letalidad)<span class="sc">/</span><span class="fu">nrow</span>(setas_test)</span>
<span id="cb137-3"><a href="modelado.html#cb137-3" aria-hidden="true" tabindex="-1"></a>error <span class="ot">=</span> <span class="dv">1</span><span class="sc">-</span>accuracy</span>
<span id="cb137-4"><a href="modelado.html#cb137-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-5"><a href="modelado.html#cb137-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto sobre el total de las setas VENENOSAS, sensitivity o recall</span></span>
<span id="cb137-6"><a href="modelado.html#cb137-6" aria-hidden="true" tabindex="-1"></a>sensitivity <span class="ot">=</span> <span class="fu">sum</span>((prediccion_knn <span class="sc">==</span> setas_test<span class="sc">$</span>Letalidad) <span class="sc">&amp;</span> (setas_test<span class="sc">$</span>Letalidad <span class="sc">==</span> <span class="dv">1</span>)) <span class="sc">/</span> <span class="fu">sum</span>(setas_test<span class="sc">$</span>Letalidad <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb137-7"><a href="modelado.html#cb137-7" aria-hidden="true" tabindex="-1"></a>recall <span class="ot">=</span> sensitivity</span>
<span id="cb137-8"><a href="modelado.html#cb137-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-9"><a href="modelado.html#cb137-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto sobre el total de las setas COMESTIBLES</span></span>
<span id="cb137-10"><a href="modelado.html#cb137-10" aria-hidden="true" tabindex="-1"></a>specificity <span class="ot">=</span>  <span class="fu">sum</span>(prediccion_knn <span class="sc">==</span> setas_test<span class="sc">$</span>Letalidad <span class="sc">&amp;</span> setas_test<span class="sc">$</span>Letalidad <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(setas_test<span class="sc">$</span>Letalidad <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb137-11"><a href="modelado.html#cb137-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-12"><a href="modelado.html#cb137-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto cuando el predicho es VENENOSAS</span></span>
<span id="cb137-13"><a href="modelado.html#cb137-13" aria-hidden="true" tabindex="-1"></a>precision <span class="ot">=</span> <span class="fu">sum</span>( (prediccion_knn<span class="sc">==</span> setas_test<span class="sc">$</span>Letalidad) <span class="sc">&amp;</span> (prediccion_knn <span class="sc">==</span> <span class="dv">1</span>))<span class="sc">/</span> <span class="fu">sum</span>(prediccion_knn <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb137-14"><a href="modelado.html#cb137-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-15"><a href="modelado.html#cb137-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto cuando el predicho es COMESTIBLE</span></span>
<span id="cb137-16"><a href="modelado.html#cb137-16" aria-hidden="true" tabindex="-1"></a>npv <span class="ot">=</span> <span class="fu">sum</span>(prediccion_knn <span class="sc">==</span> setas_test<span class="sc">$</span>Letalidad <span class="sc">&amp;</span> prediccion_knn <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(prediccion_knn <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb137-17"><a href="modelado.html#cb137-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-18"><a href="modelado.html#cb137-18" aria-hidden="true" tabindex="-1"></a><span class="co"># F1_score</span></span>
<span id="cb137-19"><a href="modelado.html#cb137-19" aria-hidden="true" tabindex="-1"></a>f1score <span class="ot">=</span> <span class="dv">2</span><span class="sc">*</span>precision<span class="sc">*</span>recall <span class="sc">/</span>(precision<span class="sc">+</span>recall)</span>
<span id="cb137-20"><a href="modelado.html#cb137-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-21"><a href="modelado.html#cb137-21" aria-hidden="true" tabindex="-1"></a><span class="co">#Tabla de medidas de precisión</span></span>
<span id="cb137-22"><a href="modelado.html#cb137-22" aria-hidden="true" tabindex="-1"></a>medidas.knn<span class="ot">=</span><span class="fu">c</span>(<span class="at">accuracy =</span> accuracy, <span class="at">error =</span> error, <span class="at">sensitivity =</span> sensitivity, <span class="at">specificity =</span> specificity, <span class="at">precision =</span> precision, <span class="at">npv =</span> npv, <span class="at">f1=</span>f1score)</span>
<span id="cb137-23"><a href="modelado.html#cb137-23" aria-hidden="true" tabindex="-1"></a>medidas.knn</span></code></pre></div>
<pre><code>##    accuracy       error sensitivity specificity   precision         npv 
## 0.998152709 0.001847291 0.998727735 0.997613365 0.997458704 0.998805257 
##          f1 
## 0.998092816</code></pre>
<p>Si usamos el 1 vecino más cercano, podemos ver en sus medidas de precisión que el ajuste es como decíamos, es decir, predice la toxicidad de las setas con un grado de acierto muy alto, solo comete un error del 0.1%.</p>
<p>Pero vamos a probar a calcular todas estas medidas con un número distinto de vecinos más cercano, por si acaso disminuyese ese pequeño error.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="modelado.html#cb139-1" aria-hidden="true" tabindex="-1"></a>k<span class="ot">=</span>(<span class="fu">dim</span>(setas60_train)[<span class="dv">1</span>]<span class="sc">^</span>(<span class="dv">4</span><span class="sc">/</span>(<span class="dv">4</span><span class="sc">+</span><span class="fu">dim</span>(setas60_train)[<span class="dv">2</span>])))<span class="sc">*</span><span class="dv">10</span></span>
<span id="cb139-2"><a href="modelado.html#cb139-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb139-3"><a href="modelado.html#cb139-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Matriz de las medidas de precision hasta 17 k-vecinos</span></span>
<span id="cb139-4"><a href="modelado.html#cb139-4" aria-hidden="true" tabindex="-1"></a>medidas_presicision<span class="ot">=</span><span class="fu">matrix</span>(<span class="at">nrow=</span><span class="fu">round</span>(k),<span class="at">ncol=</span><span class="dv">7</span>)</span>
<span id="cb139-5"><a href="modelado.html#cb139-5" aria-hidden="true" tabindex="-1"></a>nombres_medidas<span class="ot">=</span><span class="fu">c</span>(<span class="st">&quot;accuracy&quot;</span>, <span class="st">&quot;error&quot;</span>, <span class="st">&quot;sensitivity&quot;</span>, <span class="st">&quot;specificity&quot;</span>, <span class="st">&quot;precision&quot;</span>, <span class="st">&quot;npv&quot;</span>, <span class="st">&quot;f1score&quot;</span>)</span>
<span id="cb139-6"><a href="modelado.html#cb139-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(medidas_presicision)<span class="ot">=</span>nombres_medidas</span>
<span id="cb139-7"><a href="modelado.html#cb139-7" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(medidas_presicision)<span class="ot">=</span><span class="fu">seq</span>(<span class="dv">1</span>,<span class="fu">round</span>(k),<span class="dv">1</span>)</span>
<span id="cb139-8"><a href="modelado.html#cb139-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb139-9"><a href="modelado.html#cb139-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb139-10"><a href="modelado.html#cb139-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">round</span>(k)){</span>
<span id="cb139-11"><a href="modelado.html#cb139-11" aria-hidden="true" tabindex="-1"></a>  prediccion_knn<span class="ot">=</span><span class="fu">knn</span>(setas60_train,setas60_test,<span class="at">cl=</span>setas_train<span class="sc">$</span>Letalidad,<span class="at">k=</span>i)</span>
<span id="cb139-12"><a href="modelado.html#cb139-12" aria-hidden="true" tabindex="-1"></a>  medidas_presicision[i,<span class="dv">1</span>] <span class="ot">=</span> <span class="fu">sum</span>(prediccion_knn <span class="sc">==</span> setas_test<span class="sc">$</span>Letalidad)<span class="sc">/</span><span class="fu">nrow</span>(setas_test)</span>
<span id="cb139-13"><a href="modelado.html#cb139-13" aria-hidden="true" tabindex="-1"></a>  medidas_presicision[i,<span class="dv">2</span>] <span class="ot">=</span> <span class="dv">1</span><span class="sc">-</span>medidas_presicision[i,<span class="dv">1</span>]</span>
<span id="cb139-14"><a href="modelado.html#cb139-14" aria-hidden="true" tabindex="-1"></a>  medidas_presicision[i,<span class="dv">3</span>] <span class="ot">=</span> <span class="fu">sum</span>((prediccion_knn <span class="sc">==</span> setas_test<span class="sc">$</span>Letalidad) <span class="sc">&amp;</span> (setas_test<span class="sc">$</span>Letalidad <span class="sc">==</span> <span class="dv">1</span>)) <span class="sc">/</span><span class="fu">sum</span>(setas_test<span class="sc">$</span>Letalidad <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb139-15"><a href="modelado.html#cb139-15" aria-hidden="true" tabindex="-1"></a>  medidas_presicision[i,<span class="dv">4</span>] <span class="ot">=</span>  <span class="fu">sum</span>(prediccion_knn <span class="sc">==</span> setas_test<span class="sc">$</span>Letalidad <span class="sc">&amp;</span> setas_test<span class="sc">$</span>Letalidad <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(setas_test<span class="sc">$</span>Letalidad <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb139-16"><a href="modelado.html#cb139-16" aria-hidden="true" tabindex="-1"></a>  medidas_presicision[i,<span class="dv">5</span>] <span class="ot">=</span> <span class="fu">sum</span>( (prediccion_knn<span class="sc">==</span> setas_test<span class="sc">$</span>Letalidad) <span class="sc">&amp;</span> (prediccion_knn <span class="sc">==</span> <span class="dv">1</span>))<span class="sc">/</span> <span class="fu">sum</span>(prediccion_knn <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb139-17"><a href="modelado.html#cb139-17" aria-hidden="true" tabindex="-1"></a>  medidas_presicision[i,<span class="dv">6</span>] <span class="ot">=</span> <span class="fu">sum</span>(prediccion_knn <span class="sc">==</span> setas_test<span class="sc">$</span>Letalidad <span class="sc">&amp;</span> prediccion_knn <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(prediccion_knn <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb139-18"><a href="modelado.html#cb139-18" aria-hidden="true" tabindex="-1"></a>  medidas_presicision[i,<span class="dv">7</span>] <span class="ot">=</span> <span class="dv">2</span><span class="sc">*</span>medidas_presicision[i,<span class="dv">5</span>]<span class="sc">*</span>medidas_presicision[i,<span class="dv">3</span>]<span class="sc">/</span>(medidas_presicision[i,<span class="dv">5</span>]<span class="sc">+</span>medidas_presicision[i,<span class="dv">3</span>])</span>
<span id="cb139-19"><a href="modelado.html#cb139-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb139-20"><a href="modelado.html#cb139-20" aria-hidden="true" tabindex="-1"></a>medidas_presicision</span></code></pre></div>
<pre><code>##     accuracy       error sensitivity specificity precision       npv   f1score
## 1  0.9981527 0.001847291   0.9987277   0.9976134 0.9974587 0.9988053 0.9980928
## 2  0.9950739 0.004926108   0.9961832   0.9940334 0.9936548 0.9964115 0.9949174
## 3  0.9926108 0.007389163   0.9949109   0.9904535 0.9898734 0.9952038 0.9923858
## 4  0.9956897 0.004310345   0.9987277   0.9928401 0.9924147 0.9987995 0.9955612
## 5  0.9956897 0.004310345   0.9974555   0.9940334 0.9936629 0.9976048 0.9955556
## 6  0.9938424 0.006157635   0.9936387   0.9940334 0.9936387 0.9940334 0.9936387
## 7  0.9938424 0.006157635   0.9949109   0.9928401 0.9923858 0.9952153 0.9936468
## 8  0.9907635 0.009236453   0.9898219   0.9916468 0.9910828 0.9904648 0.9904519
## 9  0.9913793 0.008620690   0.9910941   0.9916468 0.9910941 0.9916468 0.9910941
## 10 0.9913793 0.008620690   0.9910941   0.9916468 0.9910941 0.9916468 0.9910941
## 11 0.9907635 0.009236453   0.9898219   0.9916468 0.9910828 0.9904648 0.9904519
## 12 0.9907635 0.009236453   0.9898219   0.9916468 0.9910828 0.9904648 0.9904519
## 13 0.9883005 0.011699507   0.9860051   0.9904535 0.9897829 0.9869203 0.9878904
## 14 0.9858374 0.014162562   0.9847328   0.9868735 0.9859873 0.9856973 0.9853596
## 15 0.9864532 0.013546798   0.9834606   0.9892601 0.9884910 0.9845606 0.9859694
## 16 0.9852217 0.014778325   0.9809160   0.9892601 0.9884615 0.9822275 0.9846743
## 17 0.9864532 0.013546798   0.9847328   0.9880668 0.9872449 0.9857143 0.9859873</code></pre>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="modelado.html#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Grafico de las medidas de precisión</span></span>
<span id="cb141-2"><a href="modelado.html#cb141-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">seq</span>(<span class="dv">1</span>,<span class="fu">round</span>(k)),medidas_presicision[,<span class="dv">1</span>],<span class="at">main=</span><span class="st">&quot;Medidas de precision&quot;</span>,<span class="at">type=</span><span class="st">&quot;n&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Número de k vecinos&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;&quot;</span>,<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),<span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="fu">round</span>(k)<span class="sc">+</span><span class="dv">2</span>))</span>
<span id="cb141-3"><a href="modelado.html#cb141-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>) {</span>
<span id="cb141-4"><a href="modelado.html#cb141-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">points</span>(<span class="fu">seq</span>(<span class="dv">1</span>,<span class="fu">round</span>(k)),medidas_presicision[,i],<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span>i<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb141-5"><a href="modelado.html#cb141-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(<span class="fu">seq</span>(<span class="dv">1</span>,<span class="fu">round</span>(k)),medidas_presicision[,i],<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span>i<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb141-6"><a href="modelado.html#cb141-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb141-7"><a href="modelado.html#cb141-7" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>,   </span>
<span id="cb141-8"><a href="modelado.html#cb141-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">inset =</span> <span class="fl">0.01</span>, </span>
<span id="cb141-9"><a href="modelado.html#cb141-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;Ac&quot;</span>,<span class="st">&quot;Er&quot;</span>, <span class="st">&quot;Se&quot;</span>,<span class="st">&quot;Sp&quot;</span>,<span class="st">&quot;Pr&quot;</span>,<span class="st">&quot;NPV&quot;</span>,<span class="st">&quot;F1&quot;</span>),</span>
<span id="cb141-10"><a href="modelado.html#cb141-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">fil =</span> <span class="fu">seq</span>(<span class="dv">2</span>, <span class="fu">round</span>(k)<span class="sc">+</span><span class="dv">1</span>))</span></code></pre></div>
<p><img src="MEMORIA_files/figure-html/knn%20cross-validation-1.png" width="672" /></p>
<p>Observamos que al ir aumentando el número de k-vecinos el error va aumentando pero sigue siendo muy pequeño, el mayor error cometido con el número de k-vecinos probado es de 1,4%, bastante despreciable como para descartar este modelo por ello.</p>
</div>
<div id="arboles-de-decisión" class="section level2" number="6.3">
<h2><span class="header-section-number">6.3</span> Arboles de Decisión</h2>
<p>Un árbol de decisión es un modelo de predicción utilizado en diversos ámbitos. Dado un conjunto de datos se fabrican diagramas de construcciones lógicas, muy similares a los sistemas de predicción basados en reglas, que sirven para representar y categorizar una serie de condiciones que ocurren de forma sucesiva, para la resolución de un problema.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="modelado.html#cb142-1" aria-hidden="true" tabindex="-1"></a>setas60_train.respuesta<span class="ot">=</span><span class="fu">data.frame</span>(<span class="fu">cbind</span>(setas_train[,<span class="dv">1</span>],setas60_train))</span>
<span id="cb142-2"><a href="modelado.html#cb142-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(setas60_train.respuesta)<span class="ot">=</span><span class="fu">c</span>(<span class="st">&quot;Letalidad&quot;</span>,<span class="fu">colnames</span>(setas60_train))</span>
<span id="cb142-3"><a href="modelado.html#cb142-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb142-4"><a href="modelado.html#cb142-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Árbol de decisión:</span></span>
<span id="cb142-5"><a href="modelado.html#cb142-5" aria-hidden="true" tabindex="-1"></a>arbol<span class="ot">=</span><span class="fu">rpart</span>(<span class="fu">as.factor</span>(setas60_train.respuesta<span class="sc">$</span>Letalidad)<span class="sc">~</span>., <span class="at">data=</span>setas60_train.respuesta,<span class="at">method=</span><span class="st">&quot;class&quot;</span>)</span>
<span id="cb142-6"><a href="modelado.html#cb142-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(arbol)</span></code></pre></div>
<pre><code>## Call:
## rpart(formula = as.factor(setas60_train.respuesta$Letalidad) ~ 
##     ., data = setas60_train.respuesta, method = &quot;class&quot;)
##   n= 4874 
## 
##           CP nsplit  rel error    xerror        xstd
## 1 0.72023810      0 1.00000000 1.0000000 0.014832389
## 2 0.04676871      1 0.27976190 0.2797619 0.010143391
## 3 0.04081633      2 0.23299320 0.2555272 0.009759411
## 4 0.01785714      3 0.19217687 0.1994048 0.008753451
## 5 0.01147959      4 0.17431973 0.1649660 0.008034621
## 6 0.01000000      9 0.09438776 0.1232993 0.007021683
## 
## Variable importance
## 1046   88 1252 1185 2279 1922 8033 7546 2793 1877 6841 2966 2696 3287 2257 2945 
##   16   16   14   13   12   12    2    1    1    1    1    1    1    1    1    1 
## 8103 2816 3084 4895 4031 
##    1    1    1    1    1 
## 
## Node number 1: 4874 observations,    complexity param=0.7202381
##   predicted class=0  expected loss=0.4825605  P(node) =1
##     class counts:  2522  2352
##    probabilities: 0.517 0.483 
##   left son=2 (2994 obs) right son=3 (1880 obs)
##   Primary splits:
##       1046 &lt; 0.6108108 to the left,  improve=1340.480, (0 missing)
##       88   &lt; 0.6108108 to the left,  improve=1330.100, (0 missing)
##       1185 &lt; 0.6108108 to the left,  improve=1143.030, (0 missing)
##       7546 &lt; 0.5615616 to the right, improve=1041.929, (0 missing)
##       1922 &lt; 0.6343402 to the left,  improve=1034.149, (0 missing)
##   Surrogate splits:
##       88   &lt; 0.6108108 to the left,  agree=0.995, adj=0.988, (0 split)
##       1185 &lt; 0.6108108 to the left,  agree=0.932, adj=0.823, (0 split)
##       1252 &lt; 0.5470085 to the left,  agree=0.895, adj=0.729, (0 split)
##       1922 &lt; 0.6343402 to the left,  agree=0.894, adj=0.724, (0 split)
##       2279 &lt; 0.5470085 to the left,  agree=0.887, adj=0.706, (0 split)
## 
## Node number 2: 2994 observations,    complexity param=0.04676871
##   predicted class=0  expected loss=0.1887108  P(node) =0.6142799
##     class counts:  2429   565
##    probabilities: 0.811 0.189 
##   left son=4 (2604 obs) right son=5 (390 obs)
##   Primary splits:
##       8033 &lt; 0.451952  to the right, improve=183.4793, (0 missing)
##       6841 &lt; 0.5067568 to the right, improve=175.4449, (0 missing)
##       4895 &lt; 0.2327327 to the right, improve=116.2098, (0 missing)
##       2274 &lt; 0.3867521 to the left,  improve=114.3779, (0 missing)
##       3294 &lt; 0.3971471 to the left,  improve=113.5999, (0 missing)
##   Surrogate splits:
##       6841 &lt; 0.5067568 to the right, agree=0.929, adj=0.451, (0 split)
##       6546 &lt; 0.3621849 to the right, agree=0.900, adj=0.233, (0 split)
##       7546 &lt; 0.5424837 to the right, agree=0.897, adj=0.208, (0 split)
##       1252 &lt; 0.1315789 to the right, agree=0.881, adj=0.085, (0 split)
##       4895 &lt; 0.1945946 to the right, agree=0.878, adj=0.062, (0 split)
## 
## Node number 3: 1880 observations,    complexity param=0.01785714
##   predicted class=1  expected loss=0.04946809  P(node) =0.3857201
##     class counts:    93  1787
##    probabilities: 0.049 0.951 
##   left son=6 (42 obs) right son=7 (1838 obs)
##   Primary splits:
##       1922 &lt; 0.507563  to the left,  improve=77.62919, (0 missing)
##       7546 &lt; 0.7472178 to the right, improve=73.91652, (0 missing)
##       2450 &lt; 0.5199147 to the left,  improve=49.58558, (0 missing)
##       4031 &lt; 0.8055556 to the right, improve=47.64144, (0 missing)
##       4735 &lt; 0.5615616 to the left,  improve=40.34677, (0 missing)
##   Surrogate splits:
##       7546 &lt; 0.7472178 to the right, agree=0.994, adj=0.714, (0 split)
##       4031 &lt; 0.8055556 to the right, agree=0.991, adj=0.619, (0 split)
##       2450 &lt; 0.451952  to the left,  agree=0.987, adj=0.429, (0 split)
##       4735 &lt; 0.451952  to the left,  agree=0.984, adj=0.262, (0 split)
##       88   &lt; 0.5945946 to the left,  agree=0.982, adj=0.190, (0 split)
## 
## Node number 4: 2604 observations,    complexity param=0.01147959
##   predicted class=0  expected loss=0.1209677  P(node) =0.5342634
##     class counts:  2289   315
##    probabilities: 0.879 0.121 
##   left son=8 (1483 obs) right son=9 (1121 obs)
##   Primary splits:
##       1046 &lt; 0.4547297 to the right, improve=66.22533, (0 missing)
##       4895 &lt; 0.2111111 to the right, improve=58.00380, (0 missing)
##       88   &lt; 0.4547297 to the right, improve=53.20137, (0 missing)
##       2274 &lt; 0.3867521 to the left,  improve=46.33612, (0 missing)
##       3294 &lt; 0.413229  to the left,  improve=44.37572, (0 missing)
##   Surrogate splits:
##       88   &lt; 0.4547297 to the right, agree=0.893, adj=0.752, (0 split)
##       1185 &lt; 0.428475  to the right, agree=0.783, adj=0.496, (0 split)
##       6841 &lt; 0.5779014 to the right, agree=0.705, adj=0.316, (0 split)
##       7546 &lt; 0.7746032 to the left,  agree=0.688, adj=0.276, (0 split)
##       4585 &lt; 0.725976  to the left,  agree=0.641, adj=0.166, (0 split)
## 
## Node number 5: 390 observations,    complexity param=0.04081633
##   predicted class=1  expected loss=0.3589744  P(node) =0.08001641
##     class counts:   140   250
##    probabilities: 0.359 0.641 
##   left son=10 (106 obs) right son=11 (284 obs)
##   Primary splits:
##       2966 &lt; 0.3423423 to the left,  improve=102.6701, (0 missing)
##       1252 &lt; 0.2327327 to the left,  improve=101.8730, (0 missing)
##       3287 &lt; 0.2268848 to the left,  improve=101.7845, (0 missing)
##       2945 &lt; 0.2802276 to the left,  improve=101.7845, (0 missing)
##       2992 &lt; 0.2268848 to the left,  improve=101.7845, (0 missing)
##   Surrogate splits:
##       3287 &lt; 0.2875375 to the left,  agree=0.985, adj=0.943, (0 split)
##       2257 &lt; 0.3598862 to the left,  agree=0.977, adj=0.915, (0 split)
##       1252 &lt; 0.2327327 to the left,  agree=0.972, adj=0.896, (0 split)
##       1877 &lt; 0.2875375 to the left,  agree=0.972, adj=0.896, (0 split)
##       2945 &lt; 0.2802276 to the left,  agree=0.969, adj=0.887, (0 split)
## 
## Node number 6: 42 observations
##   predicted class=0  expected loss=0  P(node) =0.008617152
##     class counts:    42     0
##    probabilities: 1.000 0.000 
## 
## Node number 7: 1838 observations
##   predicted class=1  expected loss=0.02774755  P(node) =0.377103
##     class counts:    51  1787
##    probabilities: 0.028 0.972 
## 
## Node number 8: 1483 observations
##   predicted class=0  expected loss=0.0229265  P(node) =0.3042675
##     class counts:  1449    34
##    probabilities: 0.977 0.023 
## 
## Node number 9: 1121 observations,    complexity param=0.01147959
##   predicted class=0  expected loss=0.250669  P(node) =0.2299959
##     class counts:   840   281
##    probabilities: 0.749 0.251 
##   left son=18 (1031 obs) right son=19 (90 obs)
##   Primary splits:
##       8103 &lt; 0.6882591 to the left,  improve=59.05920, (0 missing)
##       4283 &lt; 0.5323887 to the right, improve=55.59564, (0 missing)
##       2696 &lt; 0.4935897 to the left,  improve=47.77612, (0 missing)
##       2274 &lt; 0.4401709 to the left,  improve=46.38079, (0 missing)
##       2676 &lt; 0.5843455 to the right, improve=43.23114, (0 missing)
##   Surrogate splits:
##       4283 &lt; 0.5323887 to the right, agree=0.946, adj=0.333, (0 split)
##       5690 &lt; 0.5323887 to the right, agree=0.939, adj=0.244, (0 split)
##       3904 &lt; 0.5       to the right, agree=0.928, adj=0.100, (0 split)
##       3017 &lt; 0.4935989 to the right, agree=0.923, adj=0.044, (0 split)
##       1922 &lt; 0.6989489 to the left,  agree=0.923, adj=0.044, (0 split)
## 
## Node number 10: 106 observations
##   predicted class=0  expected loss=0.04716981  P(node) =0.02174805
##     class counts:   101     5
##    probabilities: 0.953 0.047 
## 
## Node number 11: 284 observations
##   predicted class=1  expected loss=0.1373239  P(node) =0.05826836
##     class counts:    39   245
##    probabilities: 0.137 0.863 
## 
## Node number 18: 1031 observations,    complexity param=0.01147959
##   predicted class=0  expected loss=0.2027158  P(node) =0.2115306
##     class counts:   822   209
##    probabilities: 0.797 0.203 
##   left son=36 (993 obs) right son=37 (38 obs)
##   Primary splits:
##       4895 &lt; 0.2674603 to the right, improve=37.78867, (0 missing)
##       2274 &lt; 0.3867521 to the left,  improve=30.47815, (0 missing)
##       8033 &lt; 0.5067568 to the right, improve=30.32054, (0 missing)
##       2676 &lt; 0.5843455 to the right, improve=29.38331, (0 missing)
##       7546 &lt; 0.8600954 to the left,  improve=28.57896, (0 missing)
##   Surrogate splits:
##       7546 &lt; 0.8600954 to the left,  agree=0.979, adj=0.421, (0 split)
## 
## Node number 19: 90 observations
##   predicted class=1  expected loss=0.2  P(node) =0.01846533
##     class counts:    18    72
##    probabilities: 0.200 0.800 
## 
## Node number 36: 993 observations,    complexity param=0.01147959
##   predicted class=0  expected loss=0.1762336  P(node) =0.2037341
##     class counts:   818   175
##    probabilities: 0.824 0.176 
##   left son=72 (396 obs) right son=73 (597 obs)
##   Primary splits:
##       2696 &lt; 0.4935897 to the left,  improve=36.35883, (0 missing)
##       1338 &lt; 0.4590643 to the left,  improve=31.25419, (0 missing)
##       2274 &lt; 0.402834  to the left,  improve=24.34351, (0 missing)
##       8103 &lt; 0.6363023 to the left,  improve=23.89162, (0 missing)
##       2279 &lt; 0.3598862 to the left,  improve=23.03469, (0 missing)
##   Surrogate splits:
##       1338 &lt; 0.4401709 to the left,  agree=0.941, adj=0.851, (0 split)
##       1252 &lt; 0.3867521 to the left,  agree=0.917, adj=0.793, (0 split)
##       2279 &lt; 0.3867521 to the left,  agree=0.914, adj=0.785, (0 split)
##       2793 &lt; 0.3867521 to the left,  agree=0.869, adj=0.672, (0 split)
##       1877 &lt; 0.3598862 to the left,  agree=0.857, adj=0.641, (0 split)
## 
## Node number 37: 38 observations
##   predicted class=1  expected loss=0.1052632  P(node) =0.007796471
##     class counts:     4    34
##    probabilities: 0.105 0.895 
## 
## Node number 72: 396 observations
##   predicted class=0  expected loss=0.01010101  P(node) =0.08124744
##     class counts:   392     4
##    probabilities: 0.990 0.010 
## 
## Node number 73: 597 observations,    complexity param=0.01147959
##   predicted class=0  expected loss=0.2864322  P(node) =0.1224867
##     class counts:   426   171
##    probabilities: 0.714 0.286 
##   left son=146 (437 obs) right son=147 (160 obs)
##   Primary splits:
##       1252 &lt; 0.428475  to the right, improve=126.80130, (0 missing)
##       3084 &lt; 0.428475  to the right, improve=101.37780, (0 missing)
##       2279 &lt; 0.428475  to the right, improve= 97.91515, (0 missing)
##       2676 &lt; 0.5323887 to the right, improve= 95.47279, (0 missing)
##       2793 &lt; 0.428475  to the right, improve= 92.78431, (0 missing)
##   Surrogate splits:
##       2279 &lt; 0.428475  to the right, agree=0.941, adj=0.781, (0 split)
##       2793 &lt; 0.428475  to the right, agree=0.926, adj=0.725, (0 split)
##       2696 &lt; 0.5323887 to the right, agree=0.866, adj=0.500, (0 split)
##       2816 &lt; 0.5323887 to the right, agree=0.853, adj=0.450, (0 split)
##       3084 &lt; 0.428475  to the right, agree=0.853, adj=0.450, (0 split)
## 
## Node number 146: 437 observations
##   predicted class=0  expected loss=0.08924485  P(node) =0.08965942
##     class counts:   398    39
##    probabilities: 0.911 0.089 
## 
## Node number 147: 160 observations
##   predicted class=1  expected loss=0.175  P(node) =0.03282725
##     class counts:    28   132
##    probabilities: 0.175 0.825</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="modelado.html#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(arbol)</span></code></pre></div>
<p><img src="MEMORIA_files/figure-html/arbol%20de%20decision-1.png" width="672" /></p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="modelado.html#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Tabla comparativa:</span></span>
<span id="cb145-2"><a href="modelado.html#cb145-2" aria-hidden="true" tabindex="-1"></a>setas60_test.data<span class="ot">=</span><span class="fu">as.data.frame</span>(setas60_test)</span>
<span id="cb145-3"><a href="modelado.html#cb145-3" aria-hidden="true" tabindex="-1"></a>prediccion.arbol<span class="ot">=</span><span class="fu">round</span>(<span class="fu">predict</span>(arbol,setas60_test.data)[,<span class="dv">2</span>])</span>
<span id="cb145-4"><a href="modelado.html#cb145-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(prediccion.arbol,setas_test[,<span class="dv">1</span>])</span></code></pre></div>
<pre><code>##                 
## prediccion.arbol   0   1
##                0 776  39
##                1  62 747</code></pre>
<p>El gráfico resultante podemos interpretarlo basándonos en cuánto se parece una seta a los medoides más importantes como son las observaciones 1046, 88, 1252 y 1185.</p>
<p>En la tabla podemos ver que a la hora de predecir nuestro árbol de decisión comete un error superior a lo imaginado, a continuación analizamos ese error con distintas medidas de precisión.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="modelado.html#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exactitud/Error</span></span>
<span id="cb147-2"><a href="modelado.html#cb147-2" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">=</span> <span class="fu">sum</span>(prediccion.arbol <span class="sc">==</span> setas_test[,<span class="dv">1</span>])<span class="sc">/</span><span class="fu">nrow</span>(setas60_test)</span>
<span id="cb147-3"><a href="modelado.html#cb147-3" aria-hidden="true" tabindex="-1"></a>error <span class="ot">=</span> <span class="dv">1</span><span class="sc">-</span>accuracy</span>
<span id="cb147-4"><a href="modelado.html#cb147-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-5"><a href="modelado.html#cb147-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto sobre el total de las setas VENENOSAS, sensitivity o recall</span></span>
<span id="cb147-6"><a href="modelado.html#cb147-6" aria-hidden="true" tabindex="-1"></a>sensitivity <span class="ot">=</span> <span class="fu">sum</span>((prediccion.arbol <span class="sc">==</span> setas_test[,<span class="dv">1</span>]) <span class="sc">&amp;</span> (setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">1</span>)) <span class="sc">/</span> <span class="fu">sum</span>(setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb147-7"><a href="modelado.html#cb147-7" aria-hidden="true" tabindex="-1"></a>recall <span class="ot">=</span> sensitivity</span>
<span id="cb147-8"><a href="modelado.html#cb147-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-9"><a href="modelado.html#cb147-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto sobre el total de las setas COMESTIBLES</span></span>
<span id="cb147-10"><a href="modelado.html#cb147-10" aria-hidden="true" tabindex="-1"></a>specificity <span class="ot">=</span>  <span class="fu">sum</span>(prediccion.arbol <span class="sc">==</span> setas_test[,<span class="dv">1</span>] <span class="sc">&amp;</span> setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb147-11"><a href="modelado.html#cb147-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-12"><a href="modelado.html#cb147-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto cuando el predicho es VENENOSAS</span></span>
<span id="cb147-13"><a href="modelado.html#cb147-13" aria-hidden="true" tabindex="-1"></a>precision <span class="ot">=</span> <span class="fu">sum</span>( (prediccion.arbol<span class="sc">==</span> setas_test[,<span class="dv">1</span>]) <span class="sc">&amp;</span> (prediccion.arbol <span class="sc">==</span> <span class="dv">1</span>))<span class="sc">/</span> <span class="fu">sum</span>(prediccion.arbol <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb147-14"><a href="modelado.html#cb147-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-15"><a href="modelado.html#cb147-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto cuando el predicho es COMESTIBLE</span></span>
<span id="cb147-16"><a href="modelado.html#cb147-16" aria-hidden="true" tabindex="-1"></a>npv <span class="ot">=</span> <span class="fu">sum</span>(prediccion.arbol<span class="sc">==</span> setas_test[,<span class="dv">1</span>] <span class="sc">&amp;</span> prediccion.arbol <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(prediccion.arbol <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb147-17"><a href="modelado.html#cb147-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-18"><a href="modelado.html#cb147-18" aria-hidden="true" tabindex="-1"></a><span class="co"># F1_score</span></span>
<span id="cb147-19"><a href="modelado.html#cb147-19" aria-hidden="true" tabindex="-1"></a>f1score <span class="ot">=</span> <span class="dv">2</span><span class="sc">*</span>precision<span class="sc">*</span>recall <span class="sc">/</span>(precision<span class="sc">+</span>recall)</span>
<span id="cb147-20"><a href="modelado.html#cb147-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-21"><a href="modelado.html#cb147-21" aria-hidden="true" tabindex="-1"></a><span class="co">#Tabla de medidas de precisión</span></span>
<span id="cb147-22"><a href="modelado.html#cb147-22" aria-hidden="true" tabindex="-1"></a>medidas.arboles<span class="ot">=</span><span class="fu">c</span>(<span class="at">accuracy =</span> accuracy, <span class="at">error =</span> error, <span class="at">sensitivity =</span> sensitivity, <span class="at">specificity =</span> specificity, <span class="at">precision =</span> precision, <span class="at">npv =</span> npv, <span class="at">f1=</span>f1score)</span>
<span id="cb147-23"><a href="modelado.html#cb147-23" aria-hidden="true" tabindex="-1"></a>medidas.arboles</span></code></pre></div>
<pre><code>##    accuracy       error sensitivity specificity   precision         npv 
##  0.93780788  0.06219212  0.95038168  0.92601432  0.92336218  0.95214724 
##          f1 
##  0.93667712</code></pre>
<p>El error que se comete es superior, 6%, que en el caso del modelo k-NN con el vecino más próximo, por lo que podemos determinar que el árbol de decisión predice peor.</p>
</div>
<div id="bosques-aleatorios" class="section level2" number="6.4">
<h2><span class="header-section-number">6.4</span> Bosques Aleatorios</h2>
<p>Random forest es una combinación de árboles predictores tal que cada árbol depende de los valores de un vector aleatorio probado independientemente y con la misma distribución para cada uno de estos. Es una modificación sustancial de bagging que construye una larga colección de árboles no correlacionados y luego los promedia.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="modelado.html#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">34735</span>)</span>
<span id="cb149-2"><a href="modelado.html#cb149-2" aria-hidden="true" tabindex="-1"></a>setas.rf<span class="ot">=</span><span class="fu">randomForest</span>(setas60_train, <span class="fu">as.factor</span>(setas60_train.respuesta<span class="sc">$</span>Letalidad), <span class="at">ntree=</span><span class="dv">100</span>, <span class="at">importance=</span><span class="cn">FALSE</span>, <span class="at">proximity=</span><span class="cn">TRUE</span>, <span class="at">mtry=</span><span class="dv">4</span>, <span class="at">replace=</span><span class="cn">FALSE</span>,<span class="at">method=</span><span class="st">&quot;class&quot;</span>)</span>
<span id="cb149-3"><a href="modelado.html#cb149-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-4"><a href="modelado.html#cb149-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Tabla comparativa</span></span>
<span id="cb149-5"><a href="modelado.html#cb149-5" aria-hidden="true" tabindex="-1"></a>prediccion.rf<span class="ot">=</span><span class="fu">predict</span>(setas.rf, setas60_test.data)</span>
<span id="cb149-6"><a href="modelado.html#cb149-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(prediccion.rf,<span class="fu">as.factor</span>(setas_test[,<span class="dv">1</span>]))</span></code></pre></div>
<pre><code>##              
## prediccion.rf   0   1
##             0 836   0
##             1   2 786</code></pre>
<p>La predicción es casi perfecta, pues solo se equivoca clasificando muy pocas setas. Analizamos la precisión de los bosques aleatorios con las medidas de precisión.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="modelado.html#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exactitud/Error</span></span>
<span id="cb151-2"><a href="modelado.html#cb151-2" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">=</span> <span class="fu">sum</span>(prediccion.rf <span class="sc">==</span> setas_test[,<span class="dv">1</span>])<span class="sc">/</span><span class="fu">nrow</span>(setas_test)</span>
<span id="cb151-3"><a href="modelado.html#cb151-3" aria-hidden="true" tabindex="-1"></a>error <span class="ot">=</span> <span class="dv">1</span><span class="sc">-</span>accuracy</span>
<span id="cb151-4"><a href="modelado.html#cb151-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb151-5"><a href="modelado.html#cb151-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Sensibilidad: acierto sobre el total de las setas VENENOSAS</span></span>
<span id="cb151-6"><a href="modelado.html#cb151-6" aria-hidden="true" tabindex="-1"></a>sensitivity <span class="ot">=</span> <span class="fu">sum</span>((prediccion.rf <span class="sc">==</span> setas_test[,<span class="dv">1</span>]) <span class="sc">&amp;</span> (setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">1</span>)) <span class="sc">/</span> <span class="fu">sum</span>(setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb151-7"><a href="modelado.html#cb151-7" aria-hidden="true" tabindex="-1"></a>recall <span class="ot">=</span> sensitivity</span>
<span id="cb151-8"><a href="modelado.html#cb151-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb151-9"><a href="modelado.html#cb151-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Especifidad: acierto sobre el total de las setas COMESTIBLES</span></span>
<span id="cb151-10"><a href="modelado.html#cb151-10" aria-hidden="true" tabindex="-1"></a>specificity <span class="ot">=</span>  <span class="fu">sum</span>(prediccion.rf <span class="sc">==</span> setas_test[,<span class="dv">1</span>] <span class="sc">&amp;</span> setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb151-11"><a href="modelado.html#cb151-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb151-12"><a href="modelado.html#cb151-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Precisión: acierto cuando el predicho es VENENOSAS</span></span>
<span id="cb151-13"><a href="modelado.html#cb151-13" aria-hidden="true" tabindex="-1"></a>precision <span class="ot">=</span> <span class="fu">sum</span>( (prediccion.rf<span class="sc">==</span> setas_test[,<span class="dv">1</span>]) <span class="sc">&amp;</span> (prediccion.rf <span class="sc">==</span> <span class="dv">1</span>))<span class="sc">/</span> <span class="fu">sum</span>(prediccion.rf <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb151-14"><a href="modelado.html#cb151-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb151-15"><a href="modelado.html#cb151-15" aria-hidden="true" tabindex="-1"></a><span class="co"># NPV: acierto cuando el predicho es COMESTIBLE</span></span>
<span id="cb151-16"><a href="modelado.html#cb151-16" aria-hidden="true" tabindex="-1"></a>npv <span class="ot">=</span> <span class="fu">sum</span>(prediccion.rf<span class="sc">==</span> setas_test[,<span class="dv">1</span>] <span class="sc">&amp;</span> prediccion.rf <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(prediccion.rf <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb151-17"><a href="modelado.html#cb151-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb151-18"><a href="modelado.html#cb151-18" aria-hidden="true" tabindex="-1"></a><span class="co"># F1_score</span></span>
<span id="cb151-19"><a href="modelado.html#cb151-19" aria-hidden="true" tabindex="-1"></a>f1score <span class="ot">=</span> <span class="dv">2</span><span class="sc">*</span>precision<span class="sc">*</span>recall <span class="sc">/</span>(precision<span class="sc">+</span>recall)</span>
<span id="cb151-20"><a href="modelado.html#cb151-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb151-21"><a href="modelado.html#cb151-21" aria-hidden="true" tabindex="-1"></a><span class="co">#Tabla de medidas de precisión</span></span>
<span id="cb151-22"><a href="modelado.html#cb151-22" aria-hidden="true" tabindex="-1"></a>medidas.bosques<span class="ot">=</span><span class="fu">c</span>(<span class="at">accuracy =</span> accuracy, <span class="at">error =</span> error, <span class="at">sensitivity =</span> sensitivity, <span class="at">specificity =</span> specificity, <span class="at">precision =</span> precision, <span class="at">npv =</span> npv, <span class="at">f1=</span>f1score)</span>
<span id="cb151-23"><a href="modelado.html#cb151-23" aria-hidden="true" tabindex="-1"></a>medidas.bosques</span></code></pre></div>
<pre><code>##    accuracy       error sensitivity specificity   precision         npv 
## 0.998768473 0.001231527 1.000000000 0.997613365 0.997461929 1.000000000 
##          f1 
## 0.998729352</code></pre>
<p>El error que se comete mejora respecto al algoritmo anterior, pero es parecido al error cometido por el modelo k-NN.</p>
</div>
<div id="support-vector-machines" class="section level2" number="6.5">
<h2><span class="header-section-number">6.5</span> Support Vector Machines</h2>
<p>Las máquinas de vectores soporte (del inglés support-vector machines, SVM) son un conjunto de algoritmos de aprendizaje supervisado desarrollados por Vladimir Vapnik y su equipo en los laboratorios AT&amp;T.</p>
<p>Estos métodos están propiamente relacionados con problemas de clasificación y regresión. Dado un conjunto de ejemplos de entrenamiento podemos etiquetar las clases y entrenar una SVM para construir un modelo que prediga la clase de una nueva muestra.</p>
<p>Para determinar el valor de gamma y el coste, usamos los datos que hemos reservado para validación y realizamos una estimación con ellos.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="modelado.html#cb153-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Para estimar el gamma: </span></span>
<span id="cb153-2"><a href="modelado.html#cb153-2" aria-hidden="true" tabindex="-1"></a>gamma_est<span class="ot">=</span><span class="dv">1</span><span class="sc">/</span><span class="fu">apply</span>(setas60_validacion,<span class="dv">2</span>,sd)</span>
<span id="cb153-3"><a href="modelado.html#cb153-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Para estimar el coste: </span></span>
<span id="cb153-4"><a href="modelado.html#cb153-4" aria-hidden="true" tabindex="-1"></a>norma2<span class="ot">&lt;-</span><span class="cf">function</span>(x) <span class="fu">sqrt</span>(<span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb153-5"><a href="modelado.html#cb153-5" aria-hidden="true" tabindex="-1"></a>cost_est<span class="ot">=</span><span class="fu">apply</span>(setas60_validacion,<span class="dv">2</span>,norma2)</span>
<span id="cb153-6"><a href="modelado.html#cb153-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb153-7"><a href="modelado.html#cb153-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Ajustamos el modelo</span></span>
<span id="cb153-8"><a href="modelado.html#cb153-8" aria-hidden="true" tabindex="-1"></a>setas.svm<span class="ot">=</span><span class="fu">svm</span>(setas60_train,setas_train[,<span class="dv">1</span>],<span class="at">type=</span><span class="st">&quot;C-classification&quot;</span>,<span class="at">kernel=</span><span class="st">&quot;radial&quot;</span>,<span class="at">gamma=</span><span class="fu">mean</span>(gamma_est),<span class="at">cost=</span><span class="fu">mean</span>(cost_est),<span class="at">scale=</span>F)</span>
<span id="cb153-9"><a href="modelado.html#cb153-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Vectores soporte</span></span>
<span id="cb153-10"><a href="modelado.html#cb153-10" aria-hidden="true" tabindex="-1"></a>setas.svm<span class="sc">$</span>tot.nSV</span></code></pre></div>
<pre><code>## [1] 977</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="modelado.html#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Tabla comparativa</span></span>
<span id="cb155-2"><a href="modelado.html#cb155-2" aria-hidden="true" tabindex="-1"></a>prediccion_svm<span class="ot">=</span><span class="fu">predict</span>(setas.svm,setas60_test)</span>
<span id="cb155-3"><a href="modelado.html#cb155-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(prediccion_svm,setas_test[,<span class="dv">1</span>])</span></code></pre></div>
<pre><code>##               
## prediccion_svm   0   1
##              0 838   0
##              1   0 786</code></pre>
<p>La tabla nos dice que el modelo predice a la perfección los datos, utiliza 977 vectores como soporte, lo que supone un 20% de las observaciones, por lo que descartamos que la precisión del modelo se deba a un sobre ajuste de los datos. Las medidas de precisión no van a aportar nada que no sepamos con mirar simplemente la tabla.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="modelado.html#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Medidas de precisión</span></span>
<span id="cb157-2"><a href="modelado.html#cb157-2" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">=</span> <span class="fu">sum</span>(prediccion_svm <span class="sc">==</span> setas_test[,<span class="dv">1</span>])<span class="sc">/</span><span class="fu">nrow</span>(setas_test)</span>
<span id="cb157-3"><a href="modelado.html#cb157-3" aria-hidden="true" tabindex="-1"></a>error <span class="ot">=</span> <span class="dv">1</span><span class="sc">-</span>accuracy</span>
<span id="cb157-4"><a href="modelado.html#cb157-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb157-5"><a href="modelado.html#cb157-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto sobre el total de las setas VENENOSAS, sensitivity o recall</span></span>
<span id="cb157-6"><a href="modelado.html#cb157-6" aria-hidden="true" tabindex="-1"></a>sensitivity <span class="ot">=</span> <span class="fu">sum</span>((prediccion_svm <span class="sc">==</span> setas_test[,<span class="dv">1</span>]) <span class="sc">&amp;</span> (setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">1</span>)) <span class="sc">/</span> <span class="fu">sum</span>(setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb157-7"><a href="modelado.html#cb157-7" aria-hidden="true" tabindex="-1"></a>recall <span class="ot">=</span> sensitivity</span>
<span id="cb157-8"><a href="modelado.html#cb157-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb157-9"><a href="modelado.html#cb157-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto sobre el total de las setas COMESTIBLES</span></span>
<span id="cb157-10"><a href="modelado.html#cb157-10" aria-hidden="true" tabindex="-1"></a>specificity <span class="ot">=</span>  <span class="fu">sum</span>(prediccion_svm <span class="sc">==</span> setas_test[,<span class="dv">1</span>] <span class="sc">&amp;</span> setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb157-11"><a href="modelado.html#cb157-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb157-12"><a href="modelado.html#cb157-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto cuando el predicho es VENENOSAS</span></span>
<span id="cb157-13"><a href="modelado.html#cb157-13" aria-hidden="true" tabindex="-1"></a>precision <span class="ot">=</span> <span class="fu">sum</span>((prediccion_svm<span class="sc">==</span> setas_test[,<span class="dv">1</span>]) <span class="sc">&amp;</span> (prediccion_svm <span class="sc">==</span> <span class="dv">1</span>))<span class="sc">/</span> <span class="fu">sum</span>(prediccion_svm <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb157-14"><a href="modelado.html#cb157-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb157-15"><a href="modelado.html#cb157-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto cuando el predicho es COMESTIBLE</span></span>
<span id="cb157-16"><a href="modelado.html#cb157-16" aria-hidden="true" tabindex="-1"></a>npv <span class="ot">=</span> <span class="fu">sum</span>(prediccion_svm<span class="sc">==</span> setas_test[,<span class="dv">1</span>] <span class="sc">&amp;</span> prediccion_svm <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(prediccion_svm <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb157-17"><a href="modelado.html#cb157-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb157-18"><a href="modelado.html#cb157-18" aria-hidden="true" tabindex="-1"></a><span class="co"># F1_score</span></span>
<span id="cb157-19"><a href="modelado.html#cb157-19" aria-hidden="true" tabindex="-1"></a>f1score <span class="ot">=</span> <span class="dv">2</span><span class="sc">*</span>precision<span class="sc">*</span>recall <span class="sc">/</span>(precision<span class="sc">+</span>recall)</span>
<span id="cb157-20"><a href="modelado.html#cb157-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb157-21"><a href="modelado.html#cb157-21" aria-hidden="true" tabindex="-1"></a><span class="co">#Tabla de medidas de precisión</span></span>
<span id="cb157-22"><a href="modelado.html#cb157-22" aria-hidden="true" tabindex="-1"></a>medidas.svmradial<span class="ot">=</span><span class="fu">c</span>(<span class="at">accuracy =</span> accuracy, <span class="at">error =</span> error, <span class="at">sensitivity =</span> sensitivity, <span class="at">specificity =</span> specificity, <span class="at">precision =</span> precision, <span class="at">npv =</span> npv, <span class="at">f1=</span>f1score)</span>
<span id="cb157-23"><a href="modelado.html#cb157-23" aria-hidden="true" tabindex="-1"></a>medidas.svmradial</span></code></pre></div>
<pre><code>##    accuracy       error sensitivity specificity   precision         npv 
##           1           0           1           1           1           1 
##          f1 
##           1</code></pre>
<p>Realizamos otro ajuste del modelo pero esta vez ajustando los parámetros a través de la función <em>tune.svm()</em>.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="modelado.html#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Ajustamos los parámtros</span></span>
<span id="cb159-2"><a href="modelado.html#cb159-2" aria-hidden="true" tabindex="-1"></a>parametros<span class="ot">=</span><span class="fu">tune.svm</span>(setas60_validacion, setas_validacion[,<span class="dv">1</span>], <span class="at">gamma=</span><span class="fu">seq</span>(<span class="dv">5</span>,<span class="dv">9</span>,<span class="at">by=</span><span class="fl">0.5</span>), <span class="at">cost=</span><span class="fu">seq</span>(<span class="dv">19</span>,<span class="dv">27</span>,<span class="at">by=</span><span class="dv">1</span>))</span>
<span id="cb159-3"><a href="modelado.html#cb159-3" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(parametros)</span>
<span id="cb159-4"><a href="modelado.html#cb159-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-5"><a href="modelado.html#cb159-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculamos el modelo con estos parámetros</span></span>
<span id="cb159-6"><a href="modelado.html#cb159-6" aria-hidden="true" tabindex="-1"></a>setas.svm_parametros<span class="ot">=</span><span class="fu">svm</span>(setas60_train,setas_train[,<span class="dv">1</span>], <span class="at">type=</span><span class="st">&quot;C-classification&quot;</span>, <span class="at">kernel=</span><span class="st">&quot;radial&quot;</span>, <span class="at">gamma=</span> parametros<span class="sc">$</span>best.parameters[<span class="dv">1</span>], <span class="at">cost=</span> parametros<span class="sc">$</span>best.parameters[<span class="dv">2</span>], <span class="at">scale=</span>F)</span>
<span id="cb159-7"><a href="modelado.html#cb159-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-8"><a href="modelado.html#cb159-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla comparativa</span></span>
<span id="cb159-9"><a href="modelado.html#cb159-9" aria-hidden="true" tabindex="-1"></a>prediccion_svm.parametros<span class="ot">=</span><span class="fu">predict</span>(setas.svm_parametros, setas60_test)</span>
<span id="cb159-10"><a href="modelado.html#cb159-10" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(prediccion_svm.parametros, setas_test[,<span class="dv">1</span>])</span></code></pre></div>
<p>El método no converge, por lo que toma el menor valor de ambos parámetros, lo que daría un resultado exactamente igual que usando una estimación para el parámetro gamma y cost.</p>
<p>Si realizamos el ajuste de SVM pero establecemos que el kernel es lineal, obtenemos lo siguiente:</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="modelado.html#cb160-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Para estimar el coste: </span></span>
<span id="cb160-2"><a href="modelado.html#cb160-2" aria-hidden="true" tabindex="-1"></a>norma2<span class="ot">&lt;-</span><span class="cf">function</span>(x) <span class="fu">sqrt</span>(<span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb160-3"><a href="modelado.html#cb160-3" aria-hidden="true" tabindex="-1"></a>cost_est<span class="ot">=</span><span class="fu">apply</span>(setas60_validacion,<span class="dv">2</span>,norma2)</span>
<span id="cb160-4"><a href="modelado.html#cb160-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb160-5"><a href="modelado.html#cb160-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Ajustamos el modelo</span></span>
<span id="cb160-6"><a href="modelado.html#cb160-6" aria-hidden="true" tabindex="-1"></a>setas.svm.lineal<span class="ot">=</span><span class="fu">svm</span>(setas60_train,setas_train[,<span class="dv">1</span>],<span class="at">type=</span><span class="st">&quot;C-classification&quot;</span>,<span class="at">kernel=</span><span class="st">&quot;linear&quot;</span>,<span class="at">cost=</span><span class="fu">mean</span>(cost_est),<span class="at">scale=</span>F)</span>
<span id="cb160-7"><a href="modelado.html#cb160-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Vectores soporte</span></span>
<span id="cb160-8"><a href="modelado.html#cb160-8" aria-hidden="true" tabindex="-1"></a>setas.svm.lineal<span class="sc">$</span>tot.nSV</span></code></pre></div>
<pre><code>## [1] 474</code></pre>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="modelado.html#cb162-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Tabla comparativa</span></span>
<span id="cb162-2"><a href="modelado.html#cb162-2" aria-hidden="true" tabindex="-1"></a>prediccion_svm.lineal<span class="ot">=</span><span class="fu">predict</span>(setas.svm.lineal,setas60_test)</span>
<span id="cb162-3"><a href="modelado.html#cb162-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(prediccion_svm.lineal,setas_test[,<span class="dv">1</span>])</span></code></pre></div>
<pre><code>##                      
## prediccion_svm.lineal   0   1
##                     0 812  43
##                     1  26 743</code></pre>
<p>Podemos ver que respecto al kernel radial, las predicciones empeoran. Esto lo podemos observar en las medidas de precisión.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="modelado.html#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Medidas de precisión</span></span>
<span id="cb164-2"><a href="modelado.html#cb164-2" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">=</span> <span class="fu">sum</span>(prediccion_svm.lineal <span class="sc">==</span> setas_test[,<span class="dv">1</span>])<span class="sc">/</span><span class="fu">nrow</span>(setas_test)</span>
<span id="cb164-3"><a href="modelado.html#cb164-3" aria-hidden="true" tabindex="-1"></a>error <span class="ot">=</span> <span class="dv">1</span><span class="sc">-</span>accuracy</span>
<span id="cb164-4"><a href="modelado.html#cb164-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb164-5"><a href="modelado.html#cb164-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto sobre el total de las setas VENENOSAS, sensitivity o recall</span></span>
<span id="cb164-6"><a href="modelado.html#cb164-6" aria-hidden="true" tabindex="-1"></a>sensitivity <span class="ot">=</span> <span class="fu">sum</span>((prediccion_svm.lineal <span class="sc">==</span> setas_test[,<span class="dv">1</span>]) <span class="sc">&amp;</span> (setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">1</span>)) <span class="sc">/</span> <span class="fu">sum</span>(setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb164-7"><a href="modelado.html#cb164-7" aria-hidden="true" tabindex="-1"></a>recall <span class="ot">=</span> sensitivity</span>
<span id="cb164-8"><a href="modelado.html#cb164-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb164-9"><a href="modelado.html#cb164-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto sobre el total de las setas COMESTIBLES</span></span>
<span id="cb164-10"><a href="modelado.html#cb164-10" aria-hidden="true" tabindex="-1"></a>specificity <span class="ot">=</span>  <span class="fu">sum</span>(prediccion_svm.lineal <span class="sc">==</span> setas_test[,<span class="dv">1</span>] <span class="sc">&amp;</span> setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(setas_test[,<span class="dv">1</span>] <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb164-11"><a href="modelado.html#cb164-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb164-12"><a href="modelado.html#cb164-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto cuando el predicho es VENENOSAS</span></span>
<span id="cb164-13"><a href="modelado.html#cb164-13" aria-hidden="true" tabindex="-1"></a>precision <span class="ot">=</span> <span class="fu">sum</span>((prediccion_svm.lineal<span class="sc">==</span> setas_test[,<span class="dv">1</span>]) <span class="sc">&amp;</span> (prediccion_svm.lineal <span class="sc">==</span> <span class="dv">1</span>))<span class="sc">/</span> <span class="fu">sum</span>(prediccion_svm.lineal <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb164-14"><a href="modelado.html#cb164-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb164-15"><a href="modelado.html#cb164-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Acierto cuando el predicho es COMESTIBLE</span></span>
<span id="cb164-16"><a href="modelado.html#cb164-16" aria-hidden="true" tabindex="-1"></a>npv <span class="ot">=</span> <span class="fu">sum</span>(prediccion_svm.lineal<span class="sc">==</span> setas_test[,<span class="dv">1</span>] <span class="sc">&amp;</span> prediccion_svm.lineal <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(prediccion_svm.lineal <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb164-17"><a href="modelado.html#cb164-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb164-18"><a href="modelado.html#cb164-18" aria-hidden="true" tabindex="-1"></a><span class="co"># F1_score</span></span>
<span id="cb164-19"><a href="modelado.html#cb164-19" aria-hidden="true" tabindex="-1"></a>f1score <span class="ot">=</span> <span class="dv">2</span><span class="sc">*</span>precision<span class="sc">*</span>recall <span class="sc">/</span>(precision<span class="sc">+</span>recall)</span>
<span id="cb164-20"><a href="modelado.html#cb164-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb164-21"><a href="modelado.html#cb164-21" aria-hidden="true" tabindex="-1"></a><span class="co">#Tabla de medidas de precisión</span></span>
<span id="cb164-22"><a href="modelado.html#cb164-22" aria-hidden="true" tabindex="-1"></a>medidas.svmlineal<span class="ot">=</span><span class="fu">c</span>(<span class="at">accuracy =</span> accuracy, <span class="at">error =</span> error, <span class="at">sensitivity =</span> sensitivity, <span class="at">specificity =</span> specificity, <span class="at">precision =</span> precision, <span class="at">npv =</span> npv, <span class="at">f1=</span>f1score)</span>
<span id="cb164-23"><a href="modelado.html#cb164-23" aria-hidden="true" tabindex="-1"></a>medidas.svmlineal</span></code></pre></div>
<pre><code>##    accuracy       error sensitivity specificity   precision         npv 
##  0.95751232  0.04248768  0.94529262  0.96897375  0.96618986  0.94970760 
##          f1 
##  0.95562701</code></pre>
<p>Por tanto descartaríamos usar un SVM con kernel lineal.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="preprocesado-de-datos..html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="evaluación.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": false,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
